# 数据库配置
database:
  host: localhost
  port: 3306
  user: root
  password: root
  database: sales_data_warehouse
  charset: utf8mb4
  pool_size: 5
  pool_timeout: 30

# 数据生成配置
generation:
  # 基础数据量配置
  base_metrics:
    users: 1000
    products: 500
    orders: 5000
    inventory_updates: 2000
    order_updates: 1500
  
  # 数据更新比例
  update_ratios:
    products: 0.15  # 15%的商品会更新
    users: 0.10     # 10%的用户会更新
    orders: 0.30    # 30%的订单会更新状态
    inventory: 0.20 # 20%的库存会更新
  
  # 价格变动范围
  price_changes:
    electronics: 0.30  # 电子产品价格波动±30%
    clothing: 0.20     # 服装价格波动±20%
    others: 0.10       # 其他商品价格波动±10%
  
  # 节假日调整因子
  holiday_factors:
    holiday: 1.5    # 节假日当天
    before: 1.3     # 节假日前一天
    after: 1.2      # 节假日后一天
    special:
      "11-11": 3.0  # 双11
      "12-12": 2.5  # 双12
      "06-18": 2.0  # 618
  
  # 季节性调整因子
  season_factors:
    spring: 1.1  # 春季
    summer: 1.2  # 夏季
    autumn: 0.9  # 秋季
    winter: 1.0  # 冬季
  
  # 工作日调整因子
  weekday_factors:
    monday: 0.9
    friday: 1.1
    weekend: 1.2

# 性能配置
performance:
  batch_size: 1000
  commit_interval: 7  # 每7天提交一次事务
  max_retries: 3
  retry_delay: 5  # 重试延迟（秒）

# 日志配置
logging:
  level: INFO
  file: data_generation.log
  max_size: 10485760  # 10MB
  backup_count: 5 